create schema if not exists "authenticative";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION authenticative.is_user_authenticated()
 RETURNS boolean
 LANGUAGE sql
 SECURITY DEFINER
AS $function$
  SELECT array[(select auth.jwt()->>'aal')] <@ (
    SELECT
      CASE
        WHEN count(id) > 0 THEN array['aal2']
        ELSE array['aal1', 'aal2']
      END as aal
    FROM auth.mfa_factors
    WHERE (auth.uid() = user_id)
    AND status = 'verified'
  );
$function$
;

insert into storage.buckets
  (id, name, public)
values
  ('files', 'files', false);create policy "Give users access to own folder 1m0cqf_0"
on "storage"."objects"
as permissive
for delete
to public
using (((bucket_id = 'files'::text) AND authenticative.is_user_authenticated() AND (name ~ (('^'::text || (auth.uid())::text) || '/'::text))));


create policy "Give users access to own folder 1m0cqf_1"
on "storage"."objects"
as permissive
for update
to public
using (((bucket_id = 'files'::text) AND authenticative.is_user_authenticated() AND (name ~ (('^'::text || (auth.uid())::text) || '/'::text))));


create policy "Give users access to own folder 1m0cqf_2"
on "storage"."objects"
as permissive
for insert
to public
with check (((bucket_id = 'files'::text) AND authenticative.is_user_authenticated() AND (name ~ (('^'::text || (auth.uid())::text) || '/'::text))));


create policy "Give users access to own folder 1m0cqf_3"
on "storage"."objects"
as permissive
for select
to public
using (((bucket_id = 'files'::text) AND authenticative.is_user_authenticated() AND (name ~ (('^'::text || (auth.uid())::text) || '/'::text))));



create table "public"."todo_list" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "title" text not null,
    "urgent" boolean not null default false,
    "description" text,
    "done" boolean not null default false,
    "done_at" timestamp with time zone,
    "owner" uuid not null
);


alter table "public"."todo_list" enable row level security;

CREATE UNIQUE INDEX todo_list_pkey ON public.todo_list USING btree (id);

alter table "public"."todo_list" add constraint "todo_list_pkey" PRIMARY KEY using index "todo_list_pkey";

alter table "public"."todo_list" add constraint "todo_list_owner_fkey" FOREIGN KEY (owner) REFERENCES auth.users(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."todo_list" validate constraint "todo_list_owner_fkey";

grant delete on table "public"."todo_list" to "anon";

grant insert on table "public"."todo_list" to "anon";

grant references on table "public"."todo_list" to "anon";

grant select on table "public"."todo_list" to "anon";

grant trigger on table "public"."todo_list" to "anon";

grant truncate on table "public"."todo_list" to "anon";

grant update on table "public"."todo_list" to "anon";

grant delete on table "public"."todo_list" to "authenticated";

grant insert on table "public"."todo_list" to "authenticated";

grant references on table "public"."todo_list" to "authenticated";

grant select on table "public"."todo_list" to "authenticated";

grant trigger on table "public"."todo_list" to "authenticated";

grant truncate on table "public"."todo_list" to "authenticated";

grant update on table "public"."todo_list" to "authenticated";

grant delete on table "public"."todo_list" to "service_role";

grant insert on table "public"."todo_list" to "service_role";

grant references on table "public"."todo_list" to "service_role";

grant select on table "public"."todo_list" to "service_role";

grant trigger on table "public"."todo_list" to "service_role";

grant truncate on table "public"."todo_list" to "service_role";

grant update on table "public"."todo_list" to "service_role";

create policy "Owner can do everything"
on "public"."todo_list"
as permissive
for all
to authenticated
using ((authenticative.is_user_authenticated() AND (owner = auth.uid())));



-- Multi-tenancy Support

-- 1. Create Organizations Table
create table "public"."organizations" (
    "id" uuid not null default gen_random_uuid(),
    "created_at" timestamp with time zone not null default now(),
    "name" text not null,
    "slug" text not null unique,
    "owner_id" uuid not null references auth.users(id) on delete cascade
);

alter table "public"."organizations" enable row level security;

CREATE UNIQUE INDEX organizations_pkey ON public.organizations USING btree (id);
alter table "public"."organizations" add constraint "organizations_pkey" PRIMARY KEY using index "organizations_pkey";

-- 2. Create Organization Members Table
create table "public"."organization_members" (
    "id" uuid not null default gen_random_uuid(),
    "created_at" timestamp with time zone not null default now(),
    "organization_id" uuid not null references public.organizations(id) on delete cascade,
    "user_id" uuid not null references auth.users(id) on delete cascade,
    "role" text not null default 'member' check (role in ('owner', 'admin', 'member')),
    unique(organization_id, user_id)
);

alter table "public"."organization_members" enable row level security;

CREATE UNIQUE INDEX organization_members_pkey ON public.organization_members USING btree (id);
alter table "public"."organization_members" add constraint "organization_members_pkey" PRIMARY KEY using index "organization_members_pkey";

-- 3. Update todo_list to be Org-aware
alter table "public"."todo_list" add column "org_id" uuid references public.organizations(id) on delete cascade;

-- 4. RLS Policies for Organizations
create policy "Users can view organizations they belong to"
on "public"."organizations"
for select
to authenticated
using (
    exists (
        select 1 from public.organization_members
        where organization_id = organizations.id
        and user_id = auth.uid()
    )
);

create policy "Owners can update their organizations"
on "public"."organizations"
for update
to authenticated
using (owner_id = auth.uid());

-- Trigger to add owner as member
create or replace function public.handle_new_organization()
returns trigger as $$
begin
    insert into public.organization_members (organization_id, user_id, role)
    values (new.id, new.owner_id, 'owner');
    return new;
end;
$$ language plpgsql security definer;

create trigger on_organization_created
    after insert on public.organizations
    for each row execute procedure public.handle_new_organization();

-- 5. RLS Policies for Organization Members
create policy "Members can view other members in their org"
on "public"."organization_members"
for select
to authenticated
using (
    exists (
        select 1 from public.organization_members my_membership
        where my_membership.organization_id = organization_members.organization_id
        and my_membership.user_id = auth.uid()
    )
);

-- 6. Update todo_list RLS to support Org-based access
drop policy "Owner can do everything" on "public"."todo_list";

create policy "Users can access todos in their organization"
on "public"."todo_list"
as permissive
for all
to authenticated
using (
    (authenticative.is_user_authenticated() AND (owner = auth.uid()))
    OR
    (authenticative.is_user_authenticated() AND exists (
        select 1 from public.organization_members
        where organization_id = todo_list.org_id
        and user_id = auth.uid()
    ))
);
-- Admin Support

-- Add is_admin to profiles (assuming a profiles table exists or creating one)
create table if not exists "public"."profiles" (
    "id" uuid not null references auth.users(id) on delete cascade,
    "updated_at" timestamp with time zone,
    "full_name" text,
    "avatar_url" text,
    "is_admin" boolean default false,
    primary key (id)
);

alter table "public"."profiles" enable row level security;

create policy "Public profiles are viewable by everyone."
  on profiles for select
  using ( true );

create policy "Users can insert their own profile."
  on profiles for insert
  with check ( auth.uid() = id );

create policy "Users can update own profile."
  on profiles for update
  using ( auth.uid() = id );

-- Create a profile on signup
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, full_name, avatar_url)
  values (new.id, new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'avatar_url');
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
