-- # Ahlem Platform - Complete Database Setup Script

-- 1. Security Schema & MFA Function
create schema if not exists "authenticative";

CREATE OR REPLACE FUNCTION authenticative.is_user_authenticated()
 RETURNS boolean
 LANGUAGE sql
 SECURITY DEFINER
AS $function$
  SELECT array[(select auth.jwt()->>'aal')] <@ (
    SELECT
      CASE
        WHEN count(id) > 0 THEN array['aal2']
        ELSE array['aal1', 'aal2']
      END as aal
    FROM auth.mfa_factors
    WHERE (auth.uid() = user_id)
    AND status = 'verified'
  );
$function$;

-- 2. Storage Configuration
insert into storage.buckets (id, name, public)
values ('files', 'files', false)
on conflict (id) do nothing;

create policy "Users can delete own files" on "storage"."objects" for delete to authenticated
using ((bucket_id = 'files' AND (name ~ ('^' || auth.uid()::text || '/'))));

create policy "Users can update own files" on "storage"."objects" for update to authenticated
using ((bucket_id = 'files' AND (name ~ ('^' || auth.uid()::text || '/'))));

create policy "Users can insert own files" on "storage"."objects" for insert to authenticated
with check ((bucket_id = 'files' AND (name ~ ('^' || auth.uid()::text || '/'))));

create policy "Users can select own files" on "storage"."objects" for select to authenticated
using ((bucket_id = 'files' AND (name ~ ('^' || auth.uid()::text || '/'))));

-- 3. Core Tables & Multi-tenancy
create table if not exists "public"."organizations" (
    "id" uuid not null default gen_random_uuid() primary key,
    "created_at" timestamp with time zone not null default now(),
    "name" text not null,
    "slug" text not null unique,
    "owner_id" uuid not null references auth.users(id) on delete cascade
);

alter table "public"."organizations" enable row level security;

create table if not exists "public"."organization_members" (
    "id" uuid not null default gen_random_uuid() primary key,
    "created_at" timestamp with time zone not null default now(),
    "organization_id" uuid not null references public.organizations(id) on delete cascade,
    "user_id" uuid not null references auth.users(id) on delete cascade,
    "role" text not null default 'member' check (role in ('owner', 'admin', 'member')),
    unique(organization_id, user_id)
);

alter table "public"."organization_members" enable row level security;

create table if not exists "public"."todo_list" (
    "id" bigint generated by default as identity not null primary key,
    "created_at" timestamp with time zone not null default now(),
    "title" text not null,
    "urgent" boolean not null default false,
    "description" text,
    "done" boolean not null default false,
    "done_at" timestamp with time zone,
    "owner" uuid not null references auth.users(id) on delete cascade,
    "org_id" uuid references public.organizations(id) on delete cascade
);

alter table "public"."todo_list" enable row level security;

-- 4. Profiles & Admin Logic
create table if not exists "public"."profiles" (
    "id" uuid not null references auth.users(id) on delete cascade primary key,
    "updated_at" timestamp with time zone,
    "full_name" text,
    "avatar_url" text,
    "is_admin" boolean default false
);

alter table "public"."profiles" enable row level security;

-- 5. Triggers for Automation
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, full_name, avatar_url)
  values (new.id, new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'avatar_url');
  return new;
end;
$$ language plpgsql security definer;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

create or replace function public.handle_new_organization()
returns trigger as $$
begin
    insert into public.organization_members (organization_id, user_id, role)
    values (new.id, new.owner_id, 'owner');
    return new;
end;
$$ language plpgsql security definer;

drop trigger if exists on_organization_created on public.organizations;
create trigger on_organization_created
    after insert on public.organizations
    for each row execute procedure public.handle_new_organization();

-- 6. RLS Policies
create policy "Public profiles are viewable by everyone." on profiles for select using ( true );
create policy "Users can update own profile." on profiles for update using ( auth.uid() = id );

create policy "Users can view organizations they belong to" on "public"."organizations"
for select to authenticated using (exists (select 1 from public.organization_members where organization_id = organizations.id and user_id = auth.uid()));

create policy "Owners can update their organizations" on "public"."organizations"
for update to authenticated using (owner_id = auth.uid());

create policy "Members can view other members in their org" on "public"."organization_members"
for select to authenticated using (exists (select 1 from public.organization_members my_membership where my_membership.organization_id = organization_members.organization_id and my_membership.user_id = auth.uid()));

create policy "Users can access todos in their organization" on "public"."todo_list"
as permissive for all to authenticated
using (
    (authenticative.is_user_authenticated() AND (owner = auth.uid()))
    OR
    (authenticative.is_user_authenticated() AND exists (select 1 from public.organization_members where organization_id = todo_list.org_id and user_id = auth.uid()))
);

-- 7. Admin Provisioning
-- Important: Run this command AFTER you have registered with your email.
-- UPDATE public.profiles SET is_admin = true WHERE id IN (SELECT id FROM auth.users WHERE email = 'almakhlafimohammed7@gmail.com');
