-- ══════════════════════════════════════════════════════════════════════════
--
--   EXAM Platform — قاعدة البيانات الكاملة
--   النسخة: 3.0.0
--   التاريخ: 2025
--
--   التعليمات:
--   1. افتح Supabase Dashboard → SQL Editor
--   2. انسخ هذا الملف كاملاً وشغّله
--   3. يعمل مرة واحدة فقط (آمن للتشغيل المتكرر)
--
-- ══════════════════════════════════════════════════════════════════════════

-- ─────────────────────────────────────────────────────────────────────────
-- SECTION 1: المخطط الخاص بالمصادقة
-- ─────────────────────────────────────────────────────────────────────────

create schema if not exists "authenticative";

CREATE OR REPLACE FUNCTION authenticative.is_user_authenticated()
RETURNS boolean LANGUAGE sql SECURITY DEFINER AS $function$
  SELECT array[(select auth.jwt()->>'aal')] <@ (
    SELECT CASE
      WHEN count(id) > 0 THEN array['aal2']
      ELSE array['aal1', 'aal2']
    END as aal
    FROM auth.mfa_factors
    WHERE (auth.uid() = user_id) AND status = 'verified'
  );
$function$;

-- ─────────────────────────────────────────────────────────────────────────
-- SECTION 2: التخزين (Storage)
-- ─────────────────────────────────────────────────────────────────────────

INSERT INTO storage.buckets (id, name, public)
VALUES ('files', 'files', false)
ON CONFLICT (id) DO NOTHING;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename='objects' AND policyname='Give users access to own folder 1m0cqf_0') THEN
    CREATE POLICY "Give users access to own folder 1m0cqf_0" ON storage.objects AS PERMISSIVE FOR DELETE TO public
    USING (((bucket_id = 'files'::text) AND authenticative.is_user_authenticated() AND (name ~ (('^'::text || (auth.uid())::text) || '/'::text))));
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename='objects' AND policyname='Give users access to own folder 1m0cqf_1') THEN
    CREATE POLICY "Give users access to own folder 1m0cqf_1" ON storage.objects AS PERMISSIVE FOR UPDATE TO public
    USING (((bucket_id = 'files'::text) AND authenticative.is_user_authenticated() AND (name ~ (('^'::text || (auth.uid())::text) || '/'::text))));
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename='objects' AND policyname='Give users access to own folder 1m0cqf_2') THEN
    CREATE POLICY "Give users access to own folder 1m0cqf_2" ON storage.objects AS PERMISSIVE FOR INSERT TO public
    WITH CHECK (((bucket_id = 'files'::text) AND authenticative.is_user_authenticated() AND (name ~ (('^'::text || (auth.uid())::text) || '/'::text))));
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename='objects' AND policyname='Give users access to own folder 1m0cqf_3') THEN
    CREATE POLICY "Give users access to own folder 1m0cqf_3" ON storage.objects AS PERMISSIVE FOR SELECT TO public
    USING (((bucket_id = 'files'::text) AND authenticative.is_user_authenticated() AND (name ~ (('^'::text || (auth.uid())::text) || '/'::text))));
  END IF;
END $$;

-- ─────────────────────────────────────────────────────────────────────────
-- SECTION 3: جدول الملاحظات (Todo)
-- ─────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.todo_list (
  id          bigint      GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at  timestamptz NOT NULL DEFAULT now(),
  title       text        NOT NULL,
  urgent      boolean     NOT NULL DEFAULT false,
  description text,
  done        boolean     NOT NULL DEFAULT false,
  done_at     timestamptz,
  owner       uuid        NOT NULL,
  org_id      uuid
);

ALTER TABLE public.todo_list ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='todo_list_pkey') THEN
    ALTER TABLE public.todo_list ADD CONSTRAINT todo_list_pkey PRIMARY KEY (id);
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='todo_list_owner_fkey') THEN
    ALTER TABLE public.todo_list ADD CONSTRAINT todo_list_owner_fkey
    FOREIGN KEY (owner) REFERENCES auth.users(id) ON UPDATE CASCADE ON DELETE CASCADE NOT VALID;
  END IF;
END $$;

GRANT SELECT,INSERT,UPDATE,DELETE ON public.todo_list TO anon, authenticated, service_role;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename='todo_list' AND policyname='todos_owner_policy') THEN
    CREATE POLICY "todos_owner_policy" ON public.todo_list FOR ALL USING (auth.uid() = owner);
  END IF;
END $$;

-- ─────────────────────────────────────────────────────────────────────────
-- SECTION 4: المؤسسات (Organizations)
-- ─────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.organizations (
  id          uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at  timestamptz NOT NULL DEFAULT now(),
  name        text        NOT NULL,
  owner_id    uuid        NOT NULL,
  slug        text        NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS public.organization_members (
  id              uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at      timestamptz NOT NULL DEFAULT now(),
  organization_id uuid        NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  user_id         uuid        NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  role            text        NOT NULL DEFAULT 'member'
);

ALTER TABLE public.organizations        ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.organization_members ENABLE ROW LEVEL SECURITY;

-- ─────────────────────────────────────────────────────────────────────────
-- SECTION 5: لوحة الإدارة (Admin Profiles)
-- ─────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.admin_profiles (
  id              uuid    PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  created_at      timestamptz NOT NULL DEFAULT now(),
  email           text    NOT NULL,
  is_super_admin  boolean DEFAULT false
);

ALTER TABLE public.admin_profiles ENABLE ROW LEVEL SECURITY;

-- ─────────────────────────────────────────────────────────────────────────
-- SECTION 6: ملفات تعريف المستخدمين (Profiles) — مع نظام الأدوار
-- ─────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.profiles (
  id              uuid        PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  email           text        NOT NULL,
  full_name       text,
  role            text        NOT NULL DEFAULT 'student'
                              CHECK (role IN ('owner','admin','teacher','student')),
  plan            text        NOT NULL DEFAULT 'free'
                              CHECK (plan IN ('free','pro','enterprise')),
  plan_expires_at timestamptz,
  avatar_url      text,
  is_active       boolean     NOT NULL DEFAULT true,
  is_admin        boolean     NOT NULL DEFAULT false,
  created_at      timestamptz NOT NULL DEFAULT now(),
  updated_at      timestamptz NOT NULL DEFAULT now()
);

-- إضافة أعمدة جديدة إذا لم تكن موجودة
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS role text NOT NULL DEFAULT 'student' CHECK (role IN ('owner','admin','teacher','student'));
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS plan text NOT NULL DEFAULT 'free' CHECK (plan IN ('free','pro','enterprise'));
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS full_name text;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS plan_expires_at timestamptz;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS avatar_url text;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS is_active boolean NOT NULL DEFAULT true;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS is_admin boolean NOT NULL DEFAULT false;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS updated_at timestamptz NOT NULL DEFAULT now();

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- Policies للـ profiles
DROP POLICY IF EXISTS "Users can view own profile"    ON public.profiles;
DROP POLICY IF EXISTS "Users can update own profile"  ON public.profiles;
DROP POLICY IF EXISTS "Admins can view all profiles"  ON public.profiles;
DROP POLICY IF EXISTS "Admins can update all profiles" ON public.profiles;
DROP POLICY IF EXISTS "Allow profile insert on signup" ON public.profiles;

CREATE POLICY "Users can view own profile"
  ON public.profiles FOR SELECT USING (auth.uid() = id);

CREATE POLICY "Users can update own profile"
  ON public.profiles FOR UPDATE USING (auth.uid() = id);

CREATE POLICY "Allow profile insert on signup"
  ON public.profiles FOR INSERT WITH CHECK (auth.uid() = id);

CREATE POLICY "Admins can view all profiles"
  ON public.profiles FOR SELECT
  USING (EXISTS (
    SELECT 1 FROM public.profiles p
    WHERE p.id = auth.uid() AND p.role IN ('owner','admin')
  ));

CREATE POLICY "Admins can update all profiles"
  ON public.profiles FOR UPDATE
  USING (EXISTS (
    SELECT 1 FROM public.profiles p
    WHERE p.id = auth.uid() AND p.role IN ('owner','admin')
  ));

GRANT SELECT, INSERT, UPDATE ON public.profiles TO authenticated, service_role;

-- Trigger: إنشاء profile تلقائياً عند التسجيل
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  INSERT INTO public.profiles (id, email, full_name, role, is_admin)
  VALUES (
    new.id,
    new.email,
    COALESCE(new.raw_user_meta_data->>'full_name', split_part(new.email,'@',1)),
    COALESCE(new.raw_user_meta_data->>'role', 'student'),
    false
  )
  ON CONFLICT (id) DO UPDATE SET
    email      = EXCLUDED.email,
    updated_at = now();
  RETURN new;
END;
$$;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- ─────────────────────────────────────────────────────────────────────────
-- SECTION 7: الاختبارات (Exams)
-- ─────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.exams (
  id                  uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  title               text        NOT NULL,
  description         text,
  subject             text,
  teacher_id          uuid        NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  duration_minutes    int         NOT NULL DEFAULT 30,
  max_attempts        int         NOT NULL DEFAULT 1,
  passing_score       int         NOT NULL DEFAULT 50,
  status              text        NOT NULL DEFAULT 'draft'
                                  CHECK (status IN ('draft','published','closed','archived')),
  invite_code         text        UNIQUE,
  allow_anonymous     boolean     NOT NULL DEFAULT true,
  show_results        boolean     NOT NULL DEFAULT true,
  shuffle_questions   boolean     NOT NULL DEFAULT false,
  is_paid             boolean     NOT NULL DEFAULT false,
  price               numeric(10,2),
  currency            text        DEFAULT 'USD',
  max_students        int,
  starts_at           timestamptz,
  ends_at             timestamptz,
  created_at          timestamptz NOT NULL DEFAULT now(),
  updated_at          timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.exams ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Teachers can manage own exams" ON public.exams;
DROP POLICY IF EXISTS "Published exams are viewable"  ON public.exams;
DROP POLICY IF EXISTS "Admins manage all exams"       ON public.exams;

CREATE POLICY "Teachers can manage own exams"
  ON public.exams FOR ALL USING (teacher_id = auth.uid());

CREATE POLICY "Published exams are viewable by all"
  ON public.exams FOR SELECT USING (status = 'published');

CREATE POLICY "Anyone can view published exam by invite"
  ON public.exams FOR SELECT USING (status = 'published' AND invite_code IS NOT NULL);

CREATE POLICY "Admins manage all exams"
  ON public.exams FOR ALL
  USING (EXISTS (
    SELECT 1 FROM public.profiles p
    WHERE p.id = auth.uid() AND p.role IN ('owner','admin')
  ));

GRANT SELECT, INSERT, UPDATE, DELETE ON public.exams TO authenticated;
GRANT SELECT ON public.exams TO anon;

-- ─────────────────────────────────────────────────────────────────────────
-- SECTION 8: الأسئلة (Questions)
-- ─────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.questions (
  id              uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  exam_id         uuid        NOT NULL REFERENCES public.exams(id) ON DELETE CASCADE,
  question_text   text        NOT NULL,
  question_type   text        NOT NULL DEFAULT 'mcq'
                              CHECK (question_type IN ('mcq','true_false','short_answer','essay')),
  options         jsonb,
  correct_answer  text,
  explanation     text,
  points          int         NOT NULL DEFAULT 1,
  order_index     int         NOT NULL DEFAULT 0,
  created_at      timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.questions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Teachers manage questions of own exams" ON public.questions;
DROP POLICY IF EXISTS "Questions visible during exam"          ON public.questions;

CREATE POLICY "Teachers manage questions of own exams"
  ON public.questions FOR ALL
  USING (EXISTS (
    SELECT 1 FROM public.exams e
    WHERE e.id = exam_id AND e.teacher_id = auth.uid()
  ));

CREATE POLICY "Questions visible for published exams"
  ON public.questions FOR SELECT
  USING (EXISTS (
    SELECT 1 FROM public.exams e
    WHERE e.id = exam_id AND e.status = 'published'
  ));

GRANT SELECT, INSERT, UPDATE, DELETE ON public.questions TO authenticated;
GRANT SELECT ON public.questions TO anon;

-- ─────────────────────────────────────────────────────────────────────────
-- SECTION 9: جلسات الامتحانات (Exam Sessions)
-- ─────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.exam_sessions (
  id              uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  exam_id         uuid        NOT NULL REFERENCES public.exams(id) ON DELETE CASCADE,
  student_id      uuid        REFERENCES auth.users(id) ON DELETE SET NULL,
  student_name    text        NOT NULL,
  student_email   text        NOT NULL,
  started_at      timestamptz NOT NULL DEFAULT now(),
  submitted_at    timestamptz,
  time_spent_sec  int,
  status          text        NOT NULL DEFAULT 'in_progress'
                              CHECK (status IN ('in_progress','submitted','expired')),
  answers         jsonb       DEFAULT '{}',
  score           numeric(5,2),
  passed          boolean,
  ip_address      text,
  created_at      timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.exam_sessions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Students can manage own sessions"    ON public.exam_sessions;
DROP POLICY IF EXISTS "Anonymous can insert session"        ON public.exam_sessions;
DROP POLICY IF EXISTS "Anyone can view own session by email" ON public.exam_sessions;
DROP POLICY IF EXISTS "Teachers see their exam sessions"    ON public.exam_sessions;

CREATE POLICY "Anyone can insert session (public exam)"
  ON public.exam_sessions FOR INSERT WITH CHECK (true);

CREATE POLICY "Anyone can view sessions"
  ON public.exam_sessions FOR SELECT USING (true);

CREATE POLICY "Students update own session"
  ON public.exam_sessions FOR UPDATE
  USING (student_id = auth.uid() OR student_id IS NULL);

CREATE POLICY "Teachers see their exam sessions"
  ON public.exam_sessions FOR SELECT
  USING (EXISTS (
    SELECT 1 FROM public.exams e
    WHERE e.id = exam_id AND e.teacher_id = auth.uid()
  ));

GRANT SELECT, INSERT, UPDATE ON public.exam_sessions TO authenticated, anon, service_role;

-- ─────────────────────────────────────────────────────────────────────────
-- SECTION 10: نتائج الامتحانات (Exam Results)
-- ─────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.exam_results (
  id              uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  session_id      uuid        NOT NULL REFERENCES public.exam_sessions(id) ON DELETE CASCADE,
  question_id     uuid        NOT NULL REFERENCES public.questions(id) ON DELETE CASCADE,
  student_answer  text,
  is_correct      boolean,
  points_earned   numeric(5,2) DEFAULT 0,
  feedback        text,
  created_at      timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.exam_results ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Results visible to all (for anonymous exams)"
  ON public.exam_results FOR SELECT USING (true);

CREATE POLICY "Anyone can insert results"
  ON public.exam_results FOR INSERT WITH CHECK (true);

GRANT SELECT, INSERT ON public.exam_results TO authenticated, anon, service_role;

-- ─────────────────────────────────────────────────────────────────────────
-- SECTION 11: دعوات الامتحانات (Exam Invitations)
-- ─────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.exam_invitations (
  id          uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  exam_id     uuid        NOT NULL REFERENCES public.exams(id) ON DELETE CASCADE,
  email       text        NOT NULL,
  token       text        NOT NULL UNIQUE DEFAULT encode(gen_random_bytes(32),'hex'),
  used_at     timestamptz,
  expires_at  timestamptz NOT NULL DEFAULT (now() + interval '7 days'),
  created_at  timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.exam_invitations ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Teachers manage own invitations"
  ON public.exam_invitations FOR ALL
  USING (EXISTS (
    SELECT 1 FROM public.exams e
    WHERE e.id = exam_id AND e.teacher_id = auth.uid()
  ));

CREATE POLICY "Anyone can view invitation"
  ON public.exam_invitations FOR SELECT USING (true);

GRANT SELECT, INSERT, UPDATE ON public.exam_invitations TO authenticated, anon, service_role;

-- ─────────────────────────────────────────────────────────────────────────
-- SECTION 12: الاشتراكات (Subscriptions)
-- ─────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.subscriptions (
  id                      uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id                 uuid        NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  plan                    text        NOT NULL CHECK (plan IN ('free','pro','enterprise')),
  status                  text        NOT NULL DEFAULT 'active'
                                      CHECK (status IN ('active','cancelled','expired','trialing')),
  stripe_customer_id      text,
  stripe_subscription_id  text,
  current_period_start    timestamptz,
  current_period_end      timestamptz,
  cancel_at_period_end    boolean     DEFAULT false,
  created_at              timestamptz NOT NULL DEFAULT now(),
  updated_at              timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.subscriptions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users view own subscription"
  ON public.subscriptions FOR SELECT USING (user_id = auth.uid());

CREATE POLICY "Admins manage all subscriptions"
  ON public.subscriptions FOR ALL
  USING (EXISTS (
    SELECT 1 FROM public.profiles p
    WHERE p.id = auth.uid() AND p.role IN ('owner','admin')
  ));

GRANT SELECT ON public.subscriptions TO authenticated;
GRANT INSERT, UPDATE ON public.subscriptions TO service_role;

-- ─────────────────────────────────────────────────────────────────────────
-- SECTION 13: الإشعارات (Notifications)
-- ─────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.notifications (
  id          uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id     uuid        NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  title       text        NOT NULL,
  body        text,
  type        text        NOT NULL DEFAULT 'info'
              CHECK (type IN ('info','success','warning','error','exam')),
  read        boolean     NOT NULL DEFAULT false,
  link        text,
  created_at  timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users see own notifs"
  ON public.notifications FOR ALL USING (user_id = auth.uid());

GRANT SELECT, INSERT, UPDATE, DELETE ON public.notifications TO authenticated;

-- ─────────────────────────────────────────────────────────────────────────
-- SECTION 14: سجل الأحداث (Audit Log)
-- ─────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.audit_log (
  id          bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id     uuid        REFERENCES auth.users(id) ON DELETE SET NULL,
  action      text        NOT NULL,
  entity      text,
  entity_id   text,
  meta        jsonb,
  ip          text,
  created_at  timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.audit_log ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Admins see audit log"
  ON public.audit_log FOR SELECT
  USING (EXISTS (
    SELECT 1 FROM public.profiles p
    WHERE p.id = auth.uid() AND p.role IN ('owner','admin')
  ));

GRANT SELECT, INSERT ON public.audit_log TO authenticated, service_role;

-- ─────────────────────────────────────────────────────────────────────────
-- SECTION 15: الدوال (Functions)
-- ─────────────────────────────────────────────────────────────────────────

-- توليد رمز دعوة للاختبار
CREATE OR REPLACE FUNCTION public.generate_exam_invite_code()
RETURNS text LANGUAGE sql AS $$
  SELECT upper(substring(encode(gen_random_bytes(4),'hex') FROM 1 FOR 8));
$$;

-- حساب درجة الجلسة
CREATE OR REPLACE FUNCTION public.calculate_session_score(p_session_id uuid)
RETURNS numeric LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE
  v_total_points  numeric;
  v_earned_points numeric;
BEGIN
  SELECT COALESCE(SUM(q.points), 0) INTO v_total_points
  FROM public.questions q
  JOIN public.exam_sessions s ON s.exam_id = q.exam_id
  WHERE s.id = p_session_id;

  SELECT COALESCE(SUM(r.points_earned), 0) INTO v_earned_points
  FROM public.exam_results r
  WHERE r.session_id = p_session_id;

  IF v_total_points = 0 THEN RETURN 0; END IF;
  RETURN ROUND((v_earned_points / v_total_points) * 100, 2);
END;
$$;

-- إحصاءات المنصة الكاملة (للمشرفين)
CREATE OR REPLACE FUNCTION public.get_platform_stats()
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE v jsonb;
BEGIN
  SELECT jsonb_build_object(
    'total_users',    (SELECT count(*) FROM public.profiles),
    'total_teachers', (SELECT count(*) FROM public.profiles WHERE role = 'teacher'),
    'total_students', (SELECT count(*) FROM public.profiles WHERE role = 'student'),
    'total_admins',   (SELECT count(*) FROM public.profiles WHERE role IN ('owner','admin')),
    'total_exams',    (SELECT count(*) FROM public.exams),
    'published_exams',(SELECT count(*) FROM public.exams WHERE status = 'published'),
    'total_sessions', (SELECT count(*) FROM public.exam_sessions),
    'submitted_sessions',(SELECT count(*) FROM public.exam_sessions WHERE status = 'submitted'),
    'avg_score',      COALESCE((SELECT round(avg(score)::numeric, 1) FROM public.exam_sessions WHERE score IS NOT NULL), 0),
    'pass_rate',      COALESCE((SELECT round((count(*) FILTER (WHERE passed) * 100.0 / NULLIF(count(*),0))::numeric, 1) FROM public.exam_sessions WHERE status = 'submitted'), 0)
  ) INTO v;
  RETURN v;
END;
$$;

-- إحصاءات المعلم
CREATE OR REPLACE FUNCTION public.get_teacher_stats(p_teacher_id uuid)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE v jsonb;
BEGIN
  SELECT jsonb_build_object(
    'total_exams',    (SELECT count(*) FROM public.exams WHERE teacher_id = p_teacher_id),
    'published_exams',(SELECT count(*) FROM public.exams WHERE teacher_id = p_teacher_id AND status = 'published'),
    'draft_exams',    (SELECT count(*) FROM public.exams WHERE teacher_id = p_teacher_id AND status = 'draft'),
    'total_sessions', (SELECT count(*) FROM public.exam_sessions s JOIN public.exams e ON e.id = s.exam_id WHERE e.teacher_id = p_teacher_id),
    'avg_score',      COALESCE((SELECT round(avg(s.score)::numeric,1) FROM public.exam_sessions s JOIN public.exams e ON e.id = s.exam_id WHERE e.teacher_id = p_teacher_id AND s.score IS NOT NULL), 0),
    'pass_rate',      COALESCE((SELECT round((count(*) FILTER (WHERE s.passed) * 100.0 / NULLIF(count(*),0))::numeric,1) FROM public.exam_sessions s JOIN public.exams e ON e.id = s.exam_id WHERE e.teacher_id = p_teacher_id AND s.status = 'submitted'), 0)
  ) INTO v;
  RETURN v;
END;
$$;

-- الصلاحيات على الدوال
GRANT EXECUTE ON FUNCTION public.generate_exam_invite_code()          TO authenticated, anon;
GRANT EXECUTE ON FUNCTION public.calculate_session_score(uuid)        TO authenticated, anon;
GRANT EXECUTE ON FUNCTION public.get_platform_stats()                 TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_teacher_stats(uuid)              TO authenticated;

-- ─────────────────────────────────────────────────────────────────────────
-- SECTION 16: بيانات تجريبية للبداية (يمكن تعطيلها)
-- ─────────────────────────────────────────────────────────────────────────
-- ملاحظة: البيانات التجريبية الحقيقية تُنشأ من /admin/seed في التطبيق
-- هذا القسم فارغ — يُستخدم /admin/seed بدلاً منه

-- ═══════════════════════════════════════════════════════════════════════
-- ✅ اكتمل إعداد قاعدة البيانات!
--
-- الجداول المنشأة:
--   ✓ profiles          — ملفات المستخدمين مع الأدوار
--   ✓ exams             — الاختبارات
--   ✓ questions         — الأسئلة
--   ✓ exam_sessions     — جلسات الطلاب
--   ✓ exam_results      — نتائج التصحيح
--   ✓ exam_invitations  — دعوات الإيميل
--   ✓ subscriptions     — الاشتراكات
--   ✓ notifications     — الإشعارات
--   ✓ audit_log         — سجل الأحداث
--   ✓ todo_list         — قائمة المهام
--   ✓ organizations     — المؤسسات
--
-- الدوال المنشأة:
--   ✓ generate_exam_invite_code()
--   ✓ calculate_session_score(uuid)
--   ✓ get_platform_stats()
--   ✓ get_teacher_stats(uuid)
--   ✓ handle_new_user() trigger
--
-- الخطوة التالية:
--   1. شغّل التطبيق: npm run dev
--   2. سجّل حساباً من /auth/register
--   3. شغّل SQL التالي لتعيينك كمالك:
--      UPDATE public.profiles SET role='owner', is_admin=true WHERE email='your@email.com';
--   4. اذهب إلى /admin/seed لإنشاء البيانات التجريبية
-- ═══════════════════════════════════════════════════════════════════════
