-- ══════════════════════════════════════════════════════════
--  EXAM Phase 2 & 3 — الدفع + الدعوات + البيانات التجريبية
-- ══════════════════════════════════════════════════════════

-- 1. جدول الإشعارات
CREATE TABLE IF NOT EXISTS public.notifications (
  id          uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id     uuid        NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  title       text        NOT NULL,
  body        text,
  type        text        NOT NULL DEFAULT 'info'
              CHECK (type IN ('info','success','warning','error','exam')),
  read        boolean     NOT NULL DEFAULT false,
  link        text,
  created_at  timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users see own notifs" ON public.notifications FOR ALL USING (user_id = auth.uid());
GRANT SELECT, INSERT, UPDATE, DELETE ON public.notifications TO authenticated;

-- 2. جدول سجل الأحداث (Audit Log)
CREATE TABLE IF NOT EXISTS public.audit_log (
  id          bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id     uuid        REFERENCES auth.users(id) ON DELETE SET NULL,
  action      text        NOT NULL,
  entity      text,
  entity_id   text,
  meta        jsonb,
  ip          text,
  created_at  timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.audit_log ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Admins see audit log" ON public.audit_log FOR SELECT
  USING (EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = auth.uid() AND p.role IN ('owner','admin')));
GRANT SELECT, INSERT ON public.audit_log TO authenticated, service_role;

-- 3. Function: حساب إحصاءات المنصة
CREATE OR REPLACE FUNCTION public.get_platform_stats()
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE v jsonb;
BEGIN
  SELECT jsonb_build_object(
    'total_users',    (SELECT count(*) FROM public.profiles),
    'total_teachers', (SELECT count(*) FROM public.profiles WHERE role = 'teacher'),
    'total_students', (SELECT count(*) FROM public.profiles WHERE role = 'student'),
    'total_exams',    (SELECT count(*) FROM public.exams),
    'published_exams',(SELECT count(*) FROM public.exams WHERE status = 'published'),
    'total_sessions', (SELECT count(*) FROM public.exam_sessions),
    'avg_score',      (SELECT round(avg(score)::numeric, 1) FROM public.exam_sessions WHERE score IS NOT NULL),
    'pass_rate',      (SELECT round((count(*) FILTER (WHERE passed) * 100.0 / NULLIF(count(*),0))::numeric, 1) FROM public.exam_sessions WHERE status = 'submitted')
  ) INTO v;
  RETURN v;
END;
$$;
GRANT EXECUTE ON FUNCTION public.get_platform_stats() TO authenticated;

-- 4. Function: إحصاءات المعلم
CREATE OR REPLACE FUNCTION public.get_teacher_stats(p_teacher_id uuid)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE v jsonb;
BEGIN
  SELECT jsonb_build_object(
    'total_exams',    (SELECT count(*) FROM public.exams WHERE teacher_id = p_teacher_id),
    'published_exams',(SELECT count(*) FROM public.exams WHERE teacher_id = p_teacher_id AND status = 'published'),
    'total_sessions', (SELECT count(*) FROM public.exam_sessions s JOIN public.exams e ON e.id = s.exam_id WHERE e.teacher_id = p_teacher_id),
    'avg_score',      (SELECT round(avg(s.score)::numeric,1) FROM public.exam_sessions s JOIN public.exams e ON e.id = s.exam_id WHERE e.teacher_id = p_teacher_id AND s.score IS NOT NULL),
    'pass_rate',      (SELECT round((count(*) FILTER (WHERE s.passed) * 100.0 / NULLIF(count(*),0))::numeric,1) FROM public.exam_sessions s JOIN public.exams e ON e.id = s.exam_id WHERE e.teacher_id = p_teacher_id AND s.status = 'submitted')
  ) INTO v;
  RETURN v;
END;
$$;
GRANT EXECUTE ON FUNCTION public.get_teacher_stats(uuid) TO authenticated;

-- 5. تحديث exams: إضافة حقول التسعير
ALTER TABLE public.exams
  ADD COLUMN IF NOT EXISTS is_paid       boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS price         numeric(10,2),
  ADD COLUMN IF NOT EXISTS currency      text    DEFAULT 'USD',
  ADD COLUMN IF NOT EXISTS max_students  int;

-- 6. سياسة أذونات exams_sessions للقراءة العامة
DROP POLICY IF EXISTS "Anonymous exam access (by invite)" ON public.exam_sessions;
CREATE POLICY "Anonymous can insert session"
  ON public.exam_sessions FOR INSERT WITH CHECK (true);
CREATE POLICY "Anyone can view own session by email"
  ON public.exam_sessions FOR SELECT USING (true);
